#! /bin/sh
# startup
feh --bg-fill ~/Pictures/tg_bg1.jpg
~/.config/polybar/launch.sh
compton --backend glx --paint-on-overlay --vsync opengl-swc -b &

sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Firefox desktop '^2' follow=on
bspc rule -a discord desktop '^3'
